language: node_js
node_js:
- '10'
env:
  matrix:
  - TEST_SUITE=unit
  - TEST_SUITE=e2e
  global:
  - secure: xUwqzV6LoHzGEKAnQyRLu5+WqB0IHnCXFJSiuT6Ckx6c3LW9wQ41Xs03vGgPn0aZEhYhBWlzGGuD78dLg/RZvL5QyTyIXF4HU/3MXR6deJK4rZ4uTMrVC8K3FEzpbr2m8nARsGybutInuJlhuPvenOtPAwnr+zdS7vgQbPBDHnFt21nE5+328FXTBcUo6bZErCgUwKjzgYYcKuok5ius9AqUtuK424bC11tPBhRdBVthsSomPJyffw3cbSTwyAqPxoOmoSEZu1EBndiKR+dJnWxmXIXR6sohfmrNJ/Kbbzhx3WG5v7i+Y+9VDcUZ5kX0AuwqDdcY8NO6VgMBbFmYlBXrvg7L137E20jbwDiPvM4ENTz2VIL+oZkH9DX77en5xnC+hXk8QOITOXmHyk54Hz0BRWIIstAuvCwJXIvNkwefpOESgmC1wx94Sy9ea+wekIw3bYF98LLL9/uvgrC72AIr5EEe/0Nr0YDsCQEFMM+hGivQwk9jArpFWL9Eif6HldBa73B6bfnNtqFaEWTkb+uRkDSy0TGHgZ1FYF4Y9GUq+AMSVsDoPpddpG6d44wsxxHs9U5ITOzitzeTNLNFBQPuXm2773dNCEBQ+el3bRiZ9FfICaUd6BNPXFHPyLBdUC7Bxo/MinsrS3d/7LzJpryUKqk8MxzXQtcpbKaBoYc=
  - secure: hDiQYy1VFum+2iW7wueXabil7acnitQ5YP450If7zCFXx3dyPV6+s885737JjqnUCYNnhLTe7tRk36A98YMqD2xkWtDDUlRR6FGTnoYCvf3k2PDI+xdWaPk5l+qDr3j35HgwjzkdkVmgmtMk4XIZqevhs66ZQBi3YrZKJK3FFjqHu/ZpxbskoqtCf3Zrim5ZYqNwt259iWrphOrRMi3n7e7+xCHeoEeJwT33Spu7DX0OcEZ+ITFMBQovaA8LLP0THB6OcE7pZIYhAiSbeQ6uH6WA4U40h17+AFzPtXCYYZK9eUq7V4wksCAW6bG7ZzZxIw5VpWPRC9OIsc4zWxofsxd2QVjamXkAn3TuxabnTJ/0dNPnGrK4WcckN56qF+H5IAz2nxT/x/hbwLdP1j7xlO2GAF2eDS2USdSmpDvDw+bilo9PCjMakZQV7ftYbG9ohXSY6WIsmNPA9flWWAB1Idyvi1Oo2iSLB20DNGtA04WeJn/H/kHT/rLKxZd4UMCvW+hYov6eilNPKa3/EbrImfCwi1tBIBJ1QCO/lJfFeVGy3n7Wt8aiHEqXadmMAZneUgMCABjdjwTKEZs2BT0oDI33pirKqh/DsWtMjYB89R3mHiY6pqHGJHcbzQ3ylZ9aMvbyuBP9B0nWUWZWl+35h+/MG+Ff5r6GeAt6zmKAtJE=
  - secure: tL4y19QyLcMPgDByGfPPPwKzehn7YbnY2imdQMKXFDIDdCDKvSFo7VTMvfffKpchRenb84pfT2amGEOHRxwWeRntPgLlcW5IQeN+dwg2KdL6HYvWpheWu4TD4bJ5UxxhGFZLftUk9p+lHVJlXkrDiLsX8PqVzqBdSivk16oLI6PaIX3mC6DxA7bQn8LTvMkvL57hUvk/ECozLCt2RtGjRPZNjqIyoH8Abr5ZzkIOFFDML8bOn6/Clg7bVTXUtOJgG48sTTMq96xA05gpEFa8lLC60wE7tMxeXsemaeckEb6OAhvv5NMiRjvIdSszVU77NhzyQLAAST8zRalrjHRM3SiLEuCnkZm7SE9aRCgquFDBWvJCME2ghBRMahLoGGAT0+Um0VNg5+z/L/utLTLflRkPTafy4lvvS8x30Qpt5fuqpkB2CZpAy+PBJkvzpZWO+H1LsNnlHBefu0GIOHd2cmNKebJnH0nn5e9R30p3PyKDy38g5gcWpalyT9pPwq4TxHFFa0ceZ1Z+nhr1yNRsI4CjE1gSRn30J58CF0Jv124nbsFFRs205I4tEr1ti2Hgja/+CqCRV4hM87jKJ27yjbdPcl7IhvvhcAVBAaKN56cUiYDhOn5jWvzuuORDbiZjCtowwWJbOpgAWIOVqj/vcFxRFwz28HE9cLzYvAYhJMs=
  - secure: JS8kR/1gl2nuoBifNhwVW1kNaz+i4y4FgfjBeh0tdMareAj0B1FQj/quU/TasVMH8LkoxrXGMIYrG+iimbD2Jn9Ssws772y+m7utdxmHpkMJgyrnGQ0zWunvgE9+QnnXncW7aIg9dO6YrdHH/qwV868q+zHdHHAVLx+7cj3mG3qPQaAwqxzGSttgGwfY+h2ZsEPiE83+kSD1H9uKmNtAkviA/DhaqSbiAxt8M0yHH8Qq01OhPp1J6bfZ0IbNCX0vBvEK8SQFhfn2wnDNht5kFnbKALNhCTHtq+kgITEcjh/VN0WlEOI2PEvGwFt1XbqLY08BrDpfGuvBrGxoq9EFjKjangqMJJ20d/n4rVVquAP02SSs59nD59k0roMjb0bspiREDuWR7SGpoc4PxCyPokpv0HZAVqnLkGWPmcjlpJPz/fkAw2KsH5vifHlpB2AXrpTU+mnINI/toGyPKnQzC8IYow+2oG+x1T9hF/k4neu/swlIqbI7S/FbbPU6ZYThjsGhW+oKvLekG3UURRcoDrg+U/uao4pcSDpYSE3YzTDfGTC0oImJ7Tu3KnDKFQc6T334NpIMms5CZH3M2kIB62Umce0BY3HInEkIP6ffvgfi0cehB9o6OH1tDTgq8EikEf4fM6gYC0O6BqW6qpAueSZTtBRdT+XQ4kWlBrkwLh8=
cache:
  directories:
  - "~/.cache"
install: yarn install --frozen-lockfile
before_script:
- yarn run dev &
script:
- yarn run $TEST_SUITE
- yarn build
deploy:
- provider: s3
  access_key_id: "$AWS_ACCESS_KEY_DEV"
  secret_access_key: "$AWS_SECRET_KEY_DEV"
  bucket: "$AWS_S3_BUCKET"
  region: "$AWS_REGION"
  skip_cleanup: true
  local_dir: dist
notifications:
  slack:
    secure: kZwDmcoc5inpJsMal9hhqynyfRBF1HcbToZm9ihDWZ6+AIRa+YRdziwWxXajeax7JBYUuqzaOKWnx/TnliZJcacIHxTplHQAsQspT0QwXzhiA9Stxb4/Xw21pmbp+3fcgNroCUlHY76olwpOLOa4yoMn7Y1DasT6sxbk4EqgKHxT1jXL32MECE+3XTdW9LhQHfhUbqQlpcW89bkaFJ8yPapp2p6FoA0nt+fYdRYhXIvPThXiEz+o+oOsBsnl7Xct5a5um8eh5I8lqJFjXlSMXnQP2+Yu+IawHgScW98BBjQaRjDSQx7sAhC2+ZRfTzk4C5jU2unhhrOpnVexJrlieLs9B1vuf5Qq4uZisIhrIhOxBGkehrA47hnaMVxgADMH1Tg8zDOaxAJ4qqXAG/oCAjSR/a7jR25+NPH4QFNyEGP674pwFyO9QlgytLwW7WCk9Yyk8CC9JvVS88wjWo7UIao/t/P2++PN+NM716cJBaQAcG9AUT1TXVx88HIFttCOPMLeM5DTU3BYljk7fAmAVgMDzO07Dnidq0uzxGxiW1cALKD8ooCAPxdQ1agybE3AF1a80X7Ou5AJvLLoHC2WwnosG3mOMbdsjd4T0MnUBoJmxTDgHFmMttAdfcQS2YadHi0kDQgJe5pqcEmgPXNUU8p8iauDRvI8mqHQSkBhNYU=
